//
//  RyEmoji.m
//  RTPClient
//
//  Created by kevin on 14/11/25.
//
//

#import "RyEmoji.h"

@implementation RyEmoji

+ (NSString *)emojiWithCode:(int)code {
    char chars[4];
    int len = 4;
    
    chars[0] = (code >> 24) & (1 << 24) - 1;
    chars[1] = (code >> 16) & (1 << 16) - 1;
    chars[2] = (code >> 8) & (1 << 8) - 1;
    chars[3] = code & (1 << 8) - 1;
    
    return [[NSString alloc] initWithBytes:chars
                                    length:len
                                  encoding:NSUTF32StringEncoding];
}

+ (NSArray *)recent{
    
    NSString *root = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
    NSString * user = [YTLoginUserInfo shareUserInfo].uid;
    root = [root stringByAppendingPathComponent:user];
    NSString *filePath = root;
    filePath = [filePath stringByAppendingPathComponent:@"fileCach"];
    filePath = [filePath stringByAppendingPathComponent:@"recentFace.plist"];
    NSArray * sources = [[NSMutableArray alloc] initWithContentsOfFile:filePath];
    NSMutableArray * muArray = [NSMutableArray array];
    for (int i = 0; i < sources.count && i < 20; i++) {
        NSString * tmp = [sources objectAtIndex:i];
        [muArray addObject:tmp];
    }
    return muArray?:[NSArray array];
}

+ (void)saveRecent:(NSString *)enjoyString {
    NSString *root = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) firstObject];
    NSString * user = [YTLoginUserInfo shareUserInfo].uid;
    root = [root stringByAppendingPathComponent:user];
    NSString *filePath = root;
    filePath = [filePath stringByAppendingPathComponent:@"fileCach"];
    filePath = [filePath stringByAppendingPathComponent:@"recentFace.plist"];
    
    NSMutableArray * muArray = [[NSMutableArray alloc] initWithContentsOfFile:filePath];
    if (!muArray) {
        muArray = [NSMutableArray array];
    }
    if (muArray.count >= 20) {
        [muArray removeObjectsInRange:NSMakeRange(19, muArray.count - 19)];
    }
    for (NSString * tmp in muArray) {
        if ([tmp isEqualToString:enjoyString]) {
            [muArray insertObject:enjoyString atIndex:0];
            [muArray removeObject:tmp];
            break;
        }
    }
    [muArray insertObject:enjoyString atIndex:0];
    BOOL is =  [muArray writeToFile:filePath atomically:YES];
}

+ (NSArray *)peopel
{
    NSMutableArray *array = [NSMutableArray arrayWithCapacity:50];
    [array addObject:[self emojiWithCode:0x1f604]];
    [array addObject:[self emojiWithCode:0x1f603]];
    [array addObject:[self emojiWithCode:0x1f600]];
    [array addObject:[self emojiWithCode:0x1f60a]];
    [array addObject:[self emojiWithCode:0x263a]];
    [array addObject:[self emojiWithCode:0x1f609]];
    [array addObject:[self emojiWithCode:0x1f60d]];
    [array addObject:[self emojiWithCode:0x1f618]];
    [array addObject:[self emojiWithCode:0x1f61a]];
    [array addObject:[self emojiWithCode:0x1f617]];
    [array addObject:[self emojiWithCode:0x1f619]];
    [array addObject:[self emojiWithCode:0x1f61c]];
    [array addObject:[self emojiWithCode:0x1f61d]];
    [array addObject:[self emojiWithCode:0x1f61b]];
    [array addObject:[self emojiWithCode:0x1f633]];
    [array addObject:[self emojiWithCode:0x1f601]];
    [array addObject:[self emojiWithCode:0x1f614]];
    [array addObject:[self emojiWithCode:0x1f60c]];
    [array addObject:[self emojiWithCode:0x1f612]];
    [array addObject:[self emojiWithCode:0x1f61e]];
    [array addObject:[self emojiWithCode:0x1f623]];
    [array addObject:[self emojiWithCode:0x1f622]];
    [array addObject:[self emojiWithCode:0x1f602]];
    [array addObject:[self emojiWithCode:0x1f62d]];
    [array addObject:[self emojiWithCode:0x1f62a]];
    [array addObject:[self emojiWithCode:0x1f625]];
    [array addObject:[self emojiWithCode:0x1f630]];
    [array addObject:[self emojiWithCode:0x1f605]];
    [array addObject:[self emojiWithCode:0x1f613]];
    [array addObject:[self emojiWithCode:0x1f629]];
    [array addObject:[self emojiWithCode:0x1f62b]];
    [array addObject:[self emojiWithCode:0x1f628]];
    [array addObject:[self emojiWithCode:0x1f631]];
    [array addObject:[self emojiWithCode:0x1f620]];
    [array addObject:[self emojiWithCode:0x1f621]];
    [array addObject:[self emojiWithCode:0x1f624]];
    [array addObject:[self emojiWithCode:0x1f616]];
    [array addObject:[self emojiWithCode:0x1f606]];
    [array addObject:[self emojiWithCode:0x1f60b]];
    [array addObject:[self emojiWithCode:0x1f637]];
    [array addObject:[self emojiWithCode:0x1f60e]];
    [array addObject:[self emojiWithCode:0x1f634]];
    [array addObject:[self emojiWithCode:0x1f635]];
    [array addObject:[self emojiWithCode:0x1f632]];
    [array addObject:[self emojiWithCode:0x1f61f]];
    [array addObject:[self emojiWithCode:0x1f626]];
    [array addObject:[self emojiWithCode:0x1f627]];
    [array addObject:[self emojiWithCode:0x1f608]];
    [array addObject:[self emojiWithCode:0x1f47f]];
    [array addObject:[self emojiWithCode:0x1f62e]];
    [array addObject:[self emojiWithCode:0x1f62c]];
    [array addObject:[self emojiWithCode:0x1f610]];
    [array addObject:[self emojiWithCode:0x1f615]];
    [array addObject:[self emojiWithCode:0x1f62f]];
    [array addObject:[self emojiWithCode:0x1f636]];
    [array addObject:[self emojiWithCode:0x1f607]];
    [array addObject:[self emojiWithCode:0x1f60f]];
    [array addObject:[self emojiWithCode:0x1f611]];
    [array addObject:[self emojiWithCode:0x1f472]];
    [array addObject:[self emojiWithCode:0x1f473]];
    [array addObject:[self emojiWithCode:0x1f46e]];
    [array addObject:[self emojiWithCode:0x1f477]];
    [array addObject:[self emojiWithCode:0x1f482]];
    [array addObject:[self emojiWithCode:0x1f476]];
    [array addObject:[self emojiWithCode:0x1f466]];
    [array addObject:[self emojiWithCode:0x1f467]];
    [array addObject:[self emojiWithCode:0x1f468]];
    [array addObject:[self emojiWithCode:0x1f469]];
    [array addObject:[self emojiWithCode:0x1f474]];
    [array addObject:[self emojiWithCode:0x1f475]];
    [array addObject:[self emojiWithCode:0x1f471]];
    [array addObject:[self emojiWithCode:0x1f47c]];
    [array addObject:[self emojiWithCode:0x1f478]];
    [array addObject:[self emojiWithCode:0x1f63a]];
    [array addObject:[self emojiWithCode:0x1f638]];
    [array addObject:[self emojiWithCode:0x1f63b]];
    [array addObject:[self emojiWithCode:0x1f63d]];
    [array addObject:[self emojiWithCode:0x1f63c]];
    [array addObject:[self emojiWithCode:0x1f640]];
    [array addObject:[self emojiWithCode:0x1f63f]];
    [array addObject:[self emojiWithCode:0x1f639]];
    [array addObject:[self emojiWithCode:0x1f63e]];
    [array addObject:[self emojiWithCode:0x1f479]];
    [array addObject:[self emojiWithCode:0x1f47a]];
    [array addObject:[self emojiWithCode:0x1f648]];
    [array addObject:[self emojiWithCode:0x1f649]];
    [array addObject:[self emojiWithCode:0x1f64a]];
    [array addObject:[self emojiWithCode:0x1f480]];
    [array addObject:[self emojiWithCode:0x1f47d]];
    [array addObject:[self emojiWithCode:0x1f4a9]];
    [array addObject:[self emojiWithCode:0x1f525]];
    [array addObject:[self emojiWithCode:0x2728]];
    [array addObject:[self emojiWithCode:0x1f31f]];
    [array addObject:[self emojiWithCode:0x1f4ab]];
    [array addObject:[self emojiWithCode:0x1f4a5]];
    [array addObject:[self emojiWithCode:0x1f4a2]];
    [array addObject:[self emojiWithCode:0x1f4a6]];
    [array addObject:[self emojiWithCode:0x1f4a7]];
    [array addObject:[self emojiWithCode:0x1f4a4]];
    [array addObject:[self emojiWithCode:0x1f4a8]];
    [array addObject:[self emojiWithCode:0x1f442]];
    [array addObject:[self emojiWithCode:0x1f440]];
    [array addObject:[self emojiWithCode:0x1f443]];
    [array addObject:[self emojiWithCode:0x1f445]];
    [array addObject:[self emojiWithCode:0x1f444]];
    [array addObject:[self emojiWithCode:0x1f44d]];
    [array addObject:[self emojiWithCode:0x1f44e]];
    [array addObject:[self emojiWithCode:0x1f44c]];
    [array addObject:[self emojiWithCode:0x1f44a]];
    [array addObject:[self emojiWithCode:0x270a]];
    [array addObject:[self emojiWithCode:0x270c]];
    [array addObject:[self emojiWithCode:0x1f44b]];
    [array addObject:[self emojiWithCode:0x270b]];
    [array addObject:[self emojiWithCode:0x1f450]];
    [array addObject:[self emojiWithCode:0x1f446]];
    [array addObject:[self emojiWithCode:0x1f447]];
    [array addObject:[self emojiWithCode:0x1f449]];
    [array addObject:[self emojiWithCode:0x1f448]];
    [array addObject:[self emojiWithCode:0x1f64c]];
    [array addObject:[self emojiWithCode:0x1f64f]];
    [array addObject:[self emojiWithCode:0x261d]];
    [array addObject:[self emojiWithCode:0x1f44f]];
    [array addObject:[self emojiWithCode:0x1f4aa]];
    [array addObject:[self emojiWithCode:0x1f6b6]];
    [array addObject:[self emojiWithCode:0x1f3c3]];
    [array addObject:[self emojiWithCode:0x1f483]];
    [array addObject:[self emojiWithCode:0x1f46b]];
    [array addObject:[self emojiWithCode:0x1f46a]];
    [array addObject:[self emojiWithCode:0x1f46c]];
    [array addObject:[self emojiWithCode:0x1f46d]];
    [array addObject:[self emojiWithCode:0x1f48f]];
    [array addObject:[self emojiWithCode:0x1f491]];
    [array addObject:[self emojiWithCode:0x1f46f]];
    [array addObject:[self emojiWithCode:0x1f646]];
    [array addObject:[self emojiWithCode:0x1f645]];
    [array addObject:[self emojiWithCode:0x1f481]];
    [array addObject:[self emojiWithCode:0x1f64b]];
    [array addObject:[self emojiWithCode:0x1f486]];
    [array addObject:[self emojiWithCode:0x1f487]];
    [array addObject:[self emojiWithCode:0x1f485]];
    [array addObject:[self emojiWithCode:0x1f470]];
    [array addObject:[self emojiWithCode:0x1f64e]];
    [array addObject:[self emojiWithCode:0x1f64d]];
    [array addObject:[self emojiWithCode:0x1f647]];
    [array addObject:[self emojiWithCode:0x1f3a9]];
    [array addObject:[self emojiWithCode:0x1f451]];
    [array addObject:[self emojiWithCode:0x1f452]];
    [array addObject:[self emojiWithCode:0x1f45f]];
    [array addObject:[self emojiWithCode:0x1f45e]];
    [array addObject:[self emojiWithCode:0x1f461]];
    [array addObject:[self emojiWithCode:0x1f460]];
    [array addObject:[self emojiWithCode:0x1f462]];
    [array addObject:[self emojiWithCode:0x1f455]];
    [array addObject:[self emojiWithCode:0x1f454]];
    [array addObject:[self emojiWithCode:0x1f45a]];
    [array addObject:[self emojiWithCode:0x1f457]];
    [array addObject:[self emojiWithCode:0x1f3bd]];
    [array addObject:[self emojiWithCode:0x1f456]];
    [array addObject:[self emojiWithCode:0x1f458]];
    [array addObject:[self emojiWithCode:0x1f459]];
    [array addObject:[self emojiWithCode:0x1f4bc]];
    [array addObject:[self emojiWithCode:0x1f45c]];
    [array addObject:[self emojiWithCode:0x1f45d]];
    [array addObject:[self emojiWithCode:0x1f45b]];
    [array addObject:[self emojiWithCode:0x1f453]];
    [array addObject:[self emojiWithCode:0x1f380]];
    [array addObject:[self emojiWithCode:0x1f302]];
    [array addObject:[self emojiWithCode:0x1f484]];
    [array addObject:[self emojiWithCode:0x1f49b]];
    [array addObject:[self emojiWithCode:0x1f499]];
    [array addObject:[self emojiWithCode:0x1f49c]];
    [array addObject:[self emojiWithCode:0x1f49a]];
    [array addObject:[self emojiWithCode:0x2764]];
    [array addObject:[self emojiWithCode:0x1f494]];
    [array addObject:[self emojiWithCode:0x1f497]];
    [array addObject:[self emojiWithCode:0x1f493]];
    [array addObject:[self emojiWithCode:0x1f495]];
    [array addObject:[self emojiWithCode:0x1f496]];
    [array addObject:[self emojiWithCode:0x1f49e]];
    [array addObject:[self emojiWithCode:0x1f498]];
    [array addObject:[self emojiWithCode:0x1f48c]];
    [array addObject:[self emojiWithCode:0x1f48b]];
    [array addObject:[self emojiWithCode:0x1f48d]];
    [array addObject:[self emojiWithCode:0x1f48e]];
    [array addObject:[self emojiWithCode:0x1f464]];
    [array addObject:[self emojiWithCode:0x1f465]];
    [array addObject:[self emojiWithCode:0x1f4ac]];
    [array addObject:[self emojiWithCode:0x1f463]];
    [array addObject:[self emojiWithCode:0x1f4ad]];
    return array;
}

+ (NSArray *)nature
{
    NSMutableArray *array = [NSMutableArray arrayWithCapacity:50];
    [array addObject:[self emojiWithCode:0x1f436]];
    [array addObject:[self emojiWithCode:0x1f43a]];
    [array addObject:[self emojiWithCode:0x1f431]];
    [array addObject:[self emojiWithCode:0x1f42d]];
    [array addObject:[self emojiWithCode:0x1f439]];
    [array addObject:[self emojiWithCode:0x1f430]];
    [array addObject:[self emojiWithCode:0x1f438]];
    [array addObject:[self emojiWithCode:0x1f42f]];
    [array addObject:[self emojiWithCode:0x1f428]];
    [array addObject:[self emojiWithCode:0x1f43b]];
    [array addObject:[self emojiWithCode:0x1f437]];
    [array addObject:[self emojiWithCode:0x1f43d]];
    [array addObject:[self emojiWithCode:0x1f42e]];
    [array addObject:[self emojiWithCode:0x1f417]];
    [array addObject:[self emojiWithCode:0x1f435]];
    [array addObject:[self emojiWithCode:0x1f412]];
    [array addObject:[self emojiWithCode:0x1f434]];
    [array addObject:[self emojiWithCode:0x1f411]];
    [array addObject:[self emojiWithCode:0x1f418]];
    [array addObject:[self emojiWithCode:0x1f43c]];
    [array addObject:[self emojiWithCode:0x1f427]];
    [array addObject:[self emojiWithCode:0x1f426]];
    [array addObject:[self emojiWithCode:0x1f424]];
    [array addObject:[self emojiWithCode:0x1f425]];
    [array addObject:[self emojiWithCode:0x1f423]];
    [array addObject:[self emojiWithCode:0x1f414]];
    [array addObject:[self emojiWithCode:0x1f40d]];
    [array addObject:[self emojiWithCode:0x1f422]];
    [array addObject:[self emojiWithCode:0x1f41b]];
    [array addObject:[self emojiWithCode:0x1f41d]];
    [array addObject:[self emojiWithCode:0x1f41c]];
    [array addObject:[self emojiWithCode:0x1f41e]];
    [array addObject:[self emojiWithCode:0x1f40c]];
    [array addObject:[self emojiWithCode:0x1f419]];
    [array addObject:[self emojiWithCode:0x1f41a]];
    [array addObject:[self emojiWithCode:0x1f420]];
    [array addObject:[self emojiWithCode:0x1f41f]];
    [array addObject:[self emojiWithCode:0x1f42c]];
    [array addObject:[self emojiWithCode:0x1f433]];
    [array addObject:[self emojiWithCode:0x1f40b]];
    [array addObject:[self emojiWithCode:0x1f404]];
    [array addObject:[self emojiWithCode:0x1f40f]];
    [array addObject:[self emojiWithCode:0x1f400]];
    [array addObject:[self emojiWithCode:0x1f403]];
    [array addObject:[self emojiWithCode:0x1f405]];
    [array addObject:[self emojiWithCode:0x1f407]];
    [array addObject:[self emojiWithCode:0x1f409]];
    [array addObject:[self emojiWithCode:0x1f40e]];
    [array addObject:[self emojiWithCode:0x1f410]];
    [array addObject:[self emojiWithCode:0x1f413]];
    [array addObject:[self emojiWithCode:0x1f415]];
    [array addObject:[self emojiWithCode:0x1f416]];
    [array addObject:[self emojiWithCode:0x1f401]];
    [array addObject:[self emojiWithCode:0x1f402]];
    [array addObject:[self emojiWithCode:0x1f432]];
    [array addObject:[self emojiWithCode:0x1f421]];
    [array addObject:[self emojiWithCode:0x1f40a]];
    [array addObject:[self emojiWithCode:0x1f42b]];
    [array addObject:[self emojiWithCode:0x1f42a]];
    [array addObject:[self emojiWithCode:0x1f406]];
    [array addObject:[self emojiWithCode:0x1f408]];
    [array addObject:[self emojiWithCode:0x1f429]];
    [array addObject:[self emojiWithCode:0x1f43e]];
    [array addObject:[self emojiWithCode:0x1f490]];
    [array addObject:[self emojiWithCode:0x1f338]];
    [array addObject:[self emojiWithCode:0x1f337]];
    [array addObject:[self emojiWithCode:0x1f340]];
    [array addObject:[self emojiWithCode:0x1f339]];
    [array addObject:[self emojiWithCode:0x1f33b]];
    [array addObject:[self emojiWithCode:0x1f33a]];
    [array addObject:[self emojiWithCode:0x1f341]];
    [array addObject:[self emojiWithCode:0x1f343]];
    [array addObject:[self emojiWithCode:0x1f342]];
    [array addObject:[self emojiWithCode:0x1f33f]];
    [array addObject:[self emojiWithCode:0x1f33e]];
    [array addObject:[self emojiWithCode:0x1f344]];
    [array addObject:[self emojiWithCode:0x1f335]];
    [array addObject:[self emojiWithCode:0x1f334]];
    [array addObject:[self emojiWithCode:0x1f332]];
    [array addObject:[self emojiWithCode:0x1f333]];
    [array addObject:[self emojiWithCode:0x1f330]];
    [array addObject:[self emojiWithCode:0x1f331]];
    [array addObject:[self emojiWithCode:0x1f33c]];
    [array addObject:[self emojiWithCode:0x1f310]];
    [array addObject:[self emojiWithCode:0x1f31e]];
    [array addObject:[self emojiWithCode:0x1f31d]];
    [array addObject:[self emojiWithCode:0x1f31a]];
    [array addObject:[self emojiWithCode:0x1f311]];
    [array addObject:[self emojiWithCode:0x1f312]];
    [array addObject:[self emojiWithCode:0x1f313]];
    [array addObject:[self emojiWithCode:0x1f314]];
    [array addObject:[self emojiWithCode:0x1f315]];
    [array addObject:[self emojiWithCode:0x1f316]];
    [array addObject:[self emojiWithCode:0x1f317]];
    [array addObject:[self emojiWithCode:0x1f318]];
    [array addObject:[self emojiWithCode:0x1f31c]];
    [array addObject:[self emojiWithCode:0x1f31b]];
    [array addObject:[self emojiWithCode:0x1f319]];
    [array addObject:[self emojiWithCode:0x1f30d]];
    [array addObject:[self emojiWithCode:0x1f30e]];
    [array addObject:[self emojiWithCode:0x1f30f]];
    [array addObject:[self emojiWithCode:0x1f30b]];
    [array addObject:[self emojiWithCode:0x1f30c]];
    [array addObject:[self emojiWithCode:0x1f320]];
    [array addObject:[self emojiWithCode:0x2b50]];
    [array addObject:[self emojiWithCode:0x2600]];
    [array addObject:[self emojiWithCode:0x26c5]];
    [array addObject:[self emojiWithCode:0x2601]];
    [array addObject:[self emojiWithCode:0x26a1]];
    [array addObject:[self emojiWithCode:0x2614]];
    [array addObject:[self emojiWithCode:0x2744]];
    [array addObject:[self emojiWithCode:0x26c4]];
    [array addObject:[self emojiWithCode:0x1f300]];
    [array addObject:[self emojiWithCode:0x1f301]];
    [array addObject:[self emojiWithCode:0x1f308]];
    [array addObject:[self emojiWithCode:0x1f30a]];
    return array;
}

+ (NSArray *)objects
{
    NSMutableArray *array = [NSMutableArray arrayWithCapacity:50];
    [array addObject:[self emojiWithCode:0x1f38d]];
    [array addObject:[self emojiWithCode:0x1f49d]];
    [array addObject:[self emojiWithCode:0x1f38e]];
    [array addObject:[self emojiWithCode:0x1f392]];
    [array addObject:[self emojiWithCode:0x1f393]];
    [array addObject:[self emojiWithCode:0x1f38f]];
    [array addObject:[self emojiWithCode:0x1f386]];
    [array addObject:[self emojiWithCode:0x1f387]];
    [array addObject:[self emojiWithCode:0x1f390]];
    [array addObject:[self emojiWithCode:0x1f391]];
    [array addObject:[self emojiWithCode:0x1f383]];
    [array addObject:[self emojiWithCode:0x1f47b]];
    [array addObject:[self emojiWithCode:0x1f385]];
    [array addObject:[self emojiWithCode:0x1f384]];
    [array addObject:[self emojiWithCode:0x1f381]];
    [array addObject:[self emojiWithCode:0x1f38b]];
    [array addObject:[self emojiWithCode:0x1f389]];
    [array addObject:[self emojiWithCode:0x1f38a]];
    [array addObject:[self emojiWithCode:0x1f388]];
    [array addObject:[self emojiWithCode:0x1f38c]];
    [array addObject:[self emojiWithCode:0x1f52e]];
    [array addObject:[self emojiWithCode:0x1f3a5]];
    [array addObject:[self emojiWithCode:0x1f4f7]];
    [array addObject:[self emojiWithCode:0x1f4f9]];
    [array addObject:[self emojiWithCode:0x1f4fc]];
    [array addObject:[self emojiWithCode:0x1f4bf]];
    [array addObject:[self emojiWithCode:0x1f4c0]];
    [array addObject:[self emojiWithCode:0x1f4bd]];
    [array addObject:[self emojiWithCode:0x1f4be]];
    [array addObject:[self emojiWithCode:0x1f4bb]];
    [array addObject:[self emojiWithCode:0x1f4f1]];
    [array addObject:[self emojiWithCode:0x260e]];
    [array addObject:[self emojiWithCode:0x1f4de]];
    [array addObject:[self emojiWithCode:0x1f4df]];
    [array addObject:[self emojiWithCode:0x1f4e0]];
    [array addObject:[self emojiWithCode:0x1f4e1]];
    [array addObject:[self emojiWithCode:0x1f4fa]];
    [array addObject:[self emojiWithCode:0x1f4fb]];
    [array addObject:[self emojiWithCode:0x1f508]];
    [array addObject:[self emojiWithCode:0x1f509]];
    [array addObject:[self emojiWithCode:0x1f50a]];
    [array addObject:[self emojiWithCode:0x1f507]];
    [array addObject:[self emojiWithCode:0x1f514]];
    [array addObject:[self emojiWithCode:0x1f515]];
    [array addObject:[self emojiWithCode:0x1f4e2]];
    [array addObject:[self emojiWithCode:0x1f4e3]];
    [array addObject:[self emojiWithCode:0x23f3]];
    [array addObject:[self emojiWithCode:0x231b]];
    [array addObject:[self emojiWithCode:0x23f0]];
    [array addObject:[self emojiWithCode:0x231a]];
    [array addObject:[self emojiWithCode:0x1f513]];
    [array addObject:[self emojiWithCode:0x1f512]];
    [array addObject:[self emojiWithCode:0x1f50f]];
    [array addObject:[self emojiWithCode:0x1f510]];
    [array addObject:[self emojiWithCode:0x1f511]];
    [array addObject:[self emojiWithCode:0x1f50e]];
    [array addObject:[self emojiWithCode:0x1f4a1]];
    [array addObject:[self emojiWithCode:0x1f526]];
    [array addObject:[self emojiWithCode:0x1f506]];
    [array addObject:[self emojiWithCode:0x1f505]];
    [array addObject:[self emojiWithCode:0x1f50c]];
    [array addObject:[self emojiWithCode:0x1f50b]];
    [array addObject:[self emojiWithCode:0x1f50d]];
    [array addObject:[self emojiWithCode:0x1f6c1]];
    [array addObject:[self emojiWithCode:0x1f6c0]];
    [array addObject:[self emojiWithCode:0x1f6bf]];
    [array addObject:[self emojiWithCode:0x1f6bd]];
    [array addObject:[self emojiWithCode:0x1f527]];
    [array addObject:[self emojiWithCode:0x1f529]];
    [array addObject:[self emojiWithCode:0x1f528]];
    [array addObject:[self emojiWithCode:0x1f6aa]];
    [array addObject:[self emojiWithCode:0x1f6ac]];
    [array addObject:[self emojiWithCode:0x1f4a3]];
    [array addObject:[self emojiWithCode:0x1f52b]];
    [array addObject:[self emojiWithCode:0x1f52a]];
    [array addObject:[self emojiWithCode:0x1f48a]];
    [array addObject:[self emojiWithCode:0x1f489]];
    [array addObject:[self emojiWithCode:0x1f4b0]];
    [array addObject:[self emojiWithCode:0x1f4b4]];
    [array addObject:[self emojiWithCode:0x1f4b5]];
    [array addObject:[self emojiWithCode:0x1f4b7]];
    [array addObject:[self emojiWithCode:0x1f4b6]];
    [array addObject:[self emojiWithCode:0x1f4b3]];
    [array addObject:[self emojiWithCode:0x1f4b8]];
    [array addObject:[self emojiWithCode:0x1f4f2]];
    [array addObject:[self emojiWithCode:0x1f4e7]];
    [array addObject:[self emojiWithCode:0x1f4e5]];
    [array addObject:[self emojiWithCode:0x1f4e4]];
    [array addObject:[self emojiWithCode:0x2709]];
    [array addObject:[self emojiWithCode:0x1f4e9]];
    [array addObject:[self emojiWithCode:0x1f4e8]];
    [array addObject:[self emojiWithCode:0x1f4ef]];
    [array addObject:[self emojiWithCode:0x1f4eb]];
    [array addObject:[self emojiWithCode:0x1f4ea]];
    [array addObject:[self emojiWithCode:0x1f4ec]];
    [array addObject:[self emojiWithCode:0x1f4ed]];
    [array addObject:[self emojiWithCode:0x1f4ee]];
    [array addObject:[self emojiWithCode:0x1f4e6]];
    [array addObject:[self emojiWithCode:0x1f4dd]];
    [array addObject:[self emojiWithCode:0x1f4c4]];
    [array addObject:[self emojiWithCode:0x1f4c3]];
    [array addObject:[self emojiWithCode:0x1f4d1]];
    [array addObject:[self emojiWithCode:0x1f4ca]];
    [array addObject:[self emojiWithCode:0x1f4c8]];
    [array addObject:[self emojiWithCode:0x1f4c9]];
    [array addObject:[self emojiWithCode:0x1f4dc]];
    [array addObject:[self emojiWithCode:0x1f4cb]];
    [array addObject:[self emojiWithCode:0x1f4c5]];
    [array addObject:[self emojiWithCode:0x1f4c6]];
    [array addObject:[self emojiWithCode:0x1f4c7]];
    [array addObject:[self emojiWithCode:0x1f4c1]];
    [array addObject:[self emojiWithCode:0x1f4c2]];
    [array addObject:[self emojiWithCode:0x2702]];
    [array addObject:[self emojiWithCode:0x1f4cc]];
    [array addObject:[self emojiWithCode:0x1f4ce]];
    [array addObject:[self emojiWithCode:0x2712]];
    [array addObject:[self emojiWithCode:0x270f]];
    [array addObject:[self emojiWithCode:0x1f4cf]];
    [array addObject:[self emojiWithCode:0x1f4d0]];
    [array addObject:[self emojiWithCode:0x1f4d5]];
    [array addObject:[self emojiWithCode:0x1f4d7]];
    [array addObject:[self emojiWithCode:0x1f4d8]];
    [array addObject:[self emojiWithCode:0x1f4d9]];
    [array addObject:[self emojiWithCode:0x1f4d3]];
    [array addObject:[self emojiWithCode:0x1f4d4]];
    [array addObject:[self emojiWithCode:0x1f4d2]];
    [array addObject:[self emojiWithCode:0x1f4da]];
    [array addObject:[self emojiWithCode:0x1f4d6]];
    [array addObject:[self emojiWithCode:0x1f516]];
    [array addObject:[self emojiWithCode:0x1f4db]];
    [array addObject:[self emojiWithCode:0x1f52c]];
    [array addObject:[self emojiWithCode:0x1f52d]];
    [array addObject:[self emojiWithCode:0x1f4f0]];
    [array addObject:[self emojiWithCode:0x1f3a8]];
    [array addObject:[self emojiWithCode:0x1f3ac]];
    [array addObject:[self emojiWithCode:0x1f3a4]];
    [array addObject:[self emojiWithCode:0x1f3a7]];
    [array addObject:[self emojiWithCode:0x1f3bc]];
    [array addObject:[self emojiWithCode:0x1f3b5]];
    [array addObject:[self emojiWithCode:0x1f3b6]];
    [array addObject:[self emojiWithCode:0x1f3b9]];
    [array addObject:[self emojiWithCode:0x1f3bb]];
    [array addObject:[self emojiWithCode:0x1f3ba]];
    [array addObject:[self emojiWithCode:0x1f3b7]];
    [array addObject:[self emojiWithCode:0x1f3b8]];
    [array addObject:[self emojiWithCode:0x1f47e]];
    [array addObject:[self emojiWithCode:0x1f3ae]];
    [array addObject:[self emojiWithCode:0x1f0cf]];
    [array addObject:[self emojiWithCode:0x1f3b4]];
    [array addObject:[self emojiWithCode:0x1f004]];
    [array addObject:[self emojiWithCode:0x1f3b2]];
    [array addObject:[self emojiWithCode:0x1f3af]];
    [array addObject:[self emojiWithCode:0x1f3c8]];
    [array addObject:[self emojiWithCode:0x1f3c0]];
    [array addObject:[self emojiWithCode:0x26bd]];
    [array addObject:[self emojiWithCode:0x26be]];
    [array addObject:[self emojiWithCode:0x1f3be]];
    [array addObject:[self emojiWithCode:0x1f3b1]];
    [array addObject:[self emojiWithCode:0x1f3c9]];
    [array addObject:[self emojiWithCode:0x1f3b3]];
    [array addObject:[self emojiWithCode:0x26f3]];
    [array addObject:[self emojiWithCode:0x1f6b5]];
    [array addObject:[self emojiWithCode:0x1f6b4]];
    [array addObject:[self emojiWithCode:0x1f3c1]];
    [array addObject:[self emojiWithCode:0x1f3c7]];
    [array addObject:[self emojiWithCode:0x1f3c6]];
    [array addObject:[self emojiWithCode:0x1f3bf]];
    [array addObject:[self emojiWithCode:0x1f3c2]];
    [array addObject:[self emojiWithCode:0x1f3ca]];
    [array addObject:[self emojiWithCode:0x1f3c4]];
    [array addObject:[self emojiWithCode:0x1f3a3]];
    [array addObject:[self emojiWithCode:0x2615]];
    [array addObject:[self emojiWithCode:0x1f375]];
    [array addObject:[self emojiWithCode:0x1f376]];
    [array addObject:[self emojiWithCode:0x1f37c]];
    [array addObject:[self emojiWithCode:0x1f37a]];
    [array addObject:[self emojiWithCode:0x1f37b]];
    [array addObject:[self emojiWithCode:0x1f378]];
    [array addObject:[self emojiWithCode:0x1f379]];
    [array addObject:[self emojiWithCode:0x1f377]];
    [array addObject:[self emojiWithCode:0x1f374]];
    [array addObject:[self emojiWithCode:0x1f355]];
    [array addObject:[self emojiWithCode:0x1f354]];
    [array addObject:[self emojiWithCode:0x1f35f]];
    [array addObject:[self emojiWithCode:0x1f357]];
    [array addObject:[self emojiWithCode:0x1f356]];
    [array addObject:[self emojiWithCode:0x1f35d]];
    [array addObject:[self emojiWithCode:0x1f35b]];
    [array addObject:[self emojiWithCode:0x1f364]];
    [array addObject:[self emojiWithCode:0x1f371]];
    [array addObject:[self emojiWithCode:0x1f363]];
    [array addObject:[self emojiWithCode:0x1f365]];
    [array addObject:[self emojiWithCode:0x1f359]];
    [array addObject:[self emojiWithCode:0x1f358]];
    [array addObject:[self emojiWithCode:0x1f35a]];
    [array addObject:[self emojiWithCode:0x1f35c]];
    [array addObject:[self emojiWithCode:0x1f372]];
    [array addObject:[self emojiWithCode:0x1f362]];
    [array addObject:[self emojiWithCode:0x1f361]];
    [array addObject:[self emojiWithCode:0x1f373]];
    [array addObject:[self emojiWithCode:0x1f35e]];
    [array addObject:[self emojiWithCode:0x1f369]];
    [array addObject:[self emojiWithCode:0x1f36e]];
    [array addObject:[self emojiWithCode:0x1f366]];
    [array addObject:[self emojiWithCode:0x1f368]];
    [array addObject:[self emojiWithCode:0x1f367]];
    [array addObject:[self emojiWithCode:0x1f382]];
    [array addObject:[self emojiWithCode:0x1f370]];
    [array addObject:[self emojiWithCode:0x1f36a]];
    [array addObject:[self emojiWithCode:0x1f36b]];
    [array addObject:[self emojiWithCode:0x1f36c]];
    [array addObject:[self emojiWithCode:0x1f36d]];
    [array addObject:[self emojiWithCode:0x1f36f]];
    [array addObject:[self emojiWithCode:0x1f34e]];
    [array addObject:[self emojiWithCode:0x1f34f]];
    [array addObject:[self emojiWithCode:0x1f34a]];
    [array addObject:[self emojiWithCode:0x1f34b]];
    [array addObject:[self emojiWithCode:0x1f352]];
    [array addObject:[self emojiWithCode:0x1f347]];
    [array addObject:[self emojiWithCode:0x1f349]];
    [array addObject:[self emojiWithCode:0x1f353]];
    [array addObject:[self emojiWithCode:0x1f351]];
    [array addObject:[self emojiWithCode:0x1f348]];
    [array addObject:[self emojiWithCode:0x1f34c]];
    [array addObject:[self emojiWithCode:0x1f350]];
    [array addObject:[self emojiWithCode:0x1f34d]];
    [array addObject:[self emojiWithCode:0x1f360]];
    [array addObject:[self emojiWithCode:0x1f346]];
    [array addObject:[self emojiWithCode:0x1f345]];
    [array addObject:[self emojiWithCode:0x1f33d]];
    
    return array;
}

+ (NSArray *)places
{
    NSMutableArray *array = [NSMutableArray arrayWithCapacity:50];
    [array addObject:[self emojiWithCode:0x1f3e0]];
    [array addObject:[self emojiWithCode:0x1f3e1]];
    [array addObject:[self emojiWithCode:0x1f3eb]];
    [array addObject:[self emojiWithCode:0x1f3e2]];
    [array addObject:[self emojiWithCode:0x1f3e3]];
    [array addObject:[self emojiWithCode:0x1f3e5]];
    [array addObject:[self emojiWithCode:0x1f3e6]];
    [array addObject:[self emojiWithCode:0x1f3ea]];
    [array addObject:[self emojiWithCode:0x1f3e9]];
    [array addObject:[self emojiWithCode:0x1f3e8]];
    [array addObject:[self emojiWithCode:0x1f492]];
    [array addObject:[self emojiWithCode:0x26ea]];
    [array addObject:[self emojiWithCode:0x1f3ec]];
    [array addObject:[self emojiWithCode:0x1f3e4]];
    [array addObject:[self emojiWithCode:0x1f307]];
    [array addObject:[self emojiWithCode:0x1f306]];
    [array addObject:[self emojiWithCode:0x1f3ef]];
    [array addObject:[self emojiWithCode:0x1f3f0]];
    [array addObject:[self emojiWithCode:0x26fa]];
    [array addObject:[self emojiWithCode:0x1f3ed]];
    [array addObject:[self emojiWithCode:0x1f5fc]];
    [array addObject:[self emojiWithCode:0x1f5fe]];
    [array addObject:[self emojiWithCode:0x1f5fb]];
    [array addObject:[self emojiWithCode:0x1f304]];
    [array addObject:[self emojiWithCode:0x1f305]];
    [array addObject:[self emojiWithCode:0x1f303]];
    [array addObject:[self emojiWithCode:0x1f5fd]];
    [array addObject:[self emojiWithCode:0x1f309]];
    [array addObject:[self emojiWithCode:0x1f3a0]];
    [array addObject:[self emojiWithCode:0x1f3a1]];
    [array addObject:[self emojiWithCode:0x26f2]];
    [array addObject:[self emojiWithCode:0x1f3a2]];
    [array addObject:[self emojiWithCode:0x1f6a2]];
    [array addObject:[self emojiWithCode:0x26f5]];
    [array addObject:[self emojiWithCode:0x1f6a4]];
    [array addObject:[self emojiWithCode:0x1f6a3]];
    [array addObject:[self emojiWithCode:0x2693]];
    [array addObject:[self emojiWithCode:0x1f680]];
    [array addObject:[self emojiWithCode:0x2708]];
    [array addObject:[self emojiWithCode:0x1f4ba]];
    [array addObject:[self emojiWithCode:0x1f681]];
    [array addObject:[self emojiWithCode:0x1f682]];
    [array addObject:[self emojiWithCode:0x1f68a]];
    [array addObject:[self emojiWithCode:0x1f689]];
    [array addObject:[self emojiWithCode:0x1f69e]];
    [array addObject:[self emojiWithCode:0x1f686]];
    [array addObject:[self emojiWithCode:0x1f684]];
    [array addObject:[self emojiWithCode:0x1f685]];
    [array addObject:[self emojiWithCode:0x1f688]];
    [array addObject:[self emojiWithCode:0x1f687]];
    [array addObject:[self emojiWithCode:0x1f69d]];
    [array addObject:[self emojiWithCode:0x1f68b]];
    [array addObject:[self emojiWithCode:0x1f683]];
    [array addObject:[self emojiWithCode:0x1f68e]];
    [array addObject:[self emojiWithCode:0x1f68c]];
    [array addObject:[self emojiWithCode:0x1f68d]];
    [array addObject:[self emojiWithCode:0x1f699]];
    [array addObject:[self emojiWithCode:0x1f698]];
    [array addObject:[self emojiWithCode:0x1f697]];
    [array addObject:[self emojiWithCode:0x1f695]];
    [array addObject:[self emojiWithCode:0x1f696]];
    [array addObject:[self emojiWithCode:0x1f69b]];
    [array addObject:[self emojiWithCode:0x1f69a]];
    [array addObject:[self emojiWithCode:0x1f6a8]];
    [array addObject:[self emojiWithCode:0x1f693]];
    [array addObject:[self emojiWithCode:0x1f694]];
    [array addObject:[self emojiWithCode:0x1f692]];
    [array addObject:[self emojiWithCode:0x1f691]];
    [array addObject:[self emojiWithCode:0x1f690]];
    [array addObject:[self emojiWithCode:0x1f6b2]];
    [array addObject:[self emojiWithCode:0x1f6a1]];
    [array addObject:[self emojiWithCode:0x1f69f]];
    [array addObject:[self emojiWithCode:0x1f6a0]];
    [array addObject:[self emojiWithCode:0x1f69c]];
    [array addObject:[self emojiWithCode:0x1f488]];
    [array addObject:[self emojiWithCode:0x1f68f]];
    [array addObject:[self emojiWithCode:0x1f3ab]];
    [array addObject:[self emojiWithCode:0x1f6a6]];
    [array addObject:[self emojiWithCode:0x1f6a5]];
    [array addObject:[self emojiWithCode:0x26a0]];
    [array addObject:[self emojiWithCode:0x1f6a7]];
    [array addObject:[self emojiWithCode:0x1f530]];
    [array addObject:[self emojiWithCode:0x26fd]];
    [array addObject:[self emojiWithCode:0x1f3ee]];
    [array addObject:[self emojiWithCode:0x1f3b0]];
    [array addObject:[self emojiWithCode:0x2668]];
    [array addObject:[self emojiWithCode:0x1f5ff]];
    [array addObject:[self emojiWithCode:0x1f3aa]];
    [array addObject:[self emojiWithCode:0x1f3ad]];
    [array addObject:[self emojiWithCode:0x1f4cd]];
    [array addObject:[self emojiWithCode:0x1f6a9]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddef\ud83c\uddf5"]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddf0\ud83c\uddf7"]];
//    [array addObject:[self emojiWithCode:"\ud83c\udde9\ud83c\uddea"]];
//    [array addObject:[self emojiWithCode:"\ud83c\udde8\ud83c\uddf3"]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddfa\ud83c\uddf8"]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddeb\ud83c\uddf7"]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddea\ud83c\uddf8"]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddee\ud83c\uddf9"]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddf7\ud83c\uddfa"]];
//    [array addObject:[self emojiWithCode:"\ud83c\uddec\ud83c\udde7"]];
    return array;
}

+ (NSArray *)symbols
{
    NSMutableArray *array = [NSMutableArray arrayWithCapacity:50];
//    [array addObject:[self emojiWithCode:"\u0031\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0032\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0033\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0034\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0035\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0036\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0037\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0038\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0039\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0030\u20e3"]],
//    [array addObject:[self emojiWithCode:"\u0023\u20e3"),
    [array addObject:[self emojiWithCode:0x1f51f]];
    [array addObject:[self emojiWithCode:0x1f522]];
    [array addObject:[self emojiWithCode:0x1f523]];
    [array addObject:[self emojiWithCode:0x2b06]];
    [array addObject:[self emojiWithCode:0x2b07]];
    [array addObject:[self emojiWithCode:0x2b05]];
    [array addObject:[self emojiWithCode:0x27a1]];
    [array addObject:[self emojiWithCode:0x1f520]];
    [array addObject:[self emojiWithCode:0x1f521]];
    [array addObject:[self emojiWithCode:0x1f524]];
    [array addObject:[self emojiWithCode:0x2197]];
    [array addObject:[self emojiWithCode:0x2196]];
    [array addObject:[self emojiWithCode:0x2198]];
    [array addObject:[self emojiWithCode:0x2199]];
    [array addObject:[self emojiWithCode:0x2194]];
    [array addObject:[self emojiWithCode:0x2195]];
    [array addObject:[self emojiWithCode:0x1f504]];
    [array addObject:[self emojiWithCode:0x25c0]];
    [array addObject:[self emojiWithCode:0x25b6]];
    [array addObject:[self emojiWithCode:0x1f53c]];
    [array addObject:[self emojiWithCode:0x1f53d]];
    [array addObject:[self emojiWithCode:0x21a9]];
    [array addObject:[self emojiWithCode:0x21aa]];
    [array addObject:[self emojiWithCode:0x2139]];
    [array addObject:[self emojiWithCode:0x23ea]];
    [array addObject:[self emojiWithCode:0x23e9]];
    [array addObject:[self emojiWithCode:0x23eb]];
    [array addObject:[self emojiWithCode:0x23ec]];
    [array addObject:[self emojiWithCode:0x2935]];
    [array addObject:[self emojiWithCode:0x2934]];
    [array addObject:[self emojiWithCode:0x1f197]];
    [array addObject:[self emojiWithCode:0x1f500]];
    [array addObject:[self emojiWithCode:0x1f501]];
    [array addObject:[self emojiWithCode:0x1f502]];
    [array addObject:[self emojiWithCode:0x1f195]];
    [array addObject:[self emojiWithCode:0x1f199]];
    [array addObject:[self emojiWithCode:0x1f192]];
    [array addObject:[self emojiWithCode:0x1f193]];
    [array addObject:[self emojiWithCode:0x1f196]];
    [array addObject:[self emojiWithCode:0x1f4f6]];
    [array addObject:[self emojiWithCode:0x1f3a6]];
    [array addObject:[self emojiWithCode:0x1f201]];
    [array addObject:[self emojiWithCode:0x1f22f]];
    [array addObject:[self emojiWithCode:0x1f233]];
    [array addObject:[self emojiWithCode:0x1f235]];
    [array addObject:[self emojiWithCode:0x1f234]];
    [array addObject:[self emojiWithCode:0x1f232]];
    [array addObject:[self emojiWithCode:0x1f250]];
    [array addObject:[self emojiWithCode:0x1f239]];
    [array addObject:[self emojiWithCode:0x1f23a]];
    [array addObject:[self emojiWithCode:0x1f236]];
    [array addObject:[self emojiWithCode:0x1f21a]];
    [array addObject:[self emojiWithCode:0x1f6bb]];
    [array addObject:[self emojiWithCode:0x1f6b9]];
    [array addObject:[self emojiWithCode:0x1f6ba]];
    [array addObject:[self emojiWithCode:0x1f6bc]];
    [array addObject:[self emojiWithCode:0x1f6be]];
    [array addObject:[self emojiWithCode:0x1f6b0]];
    [array addObject:[self emojiWithCode:0x1f6ae]];
    [array addObject:[self emojiWithCode:0x1f17f]];
    [array addObject:[self emojiWithCode:0x267f]];
    [array addObject:[self emojiWithCode:0x1f6ad]];
    [array addObject:[self emojiWithCode:0x1f237]];
    [array addObject:[self emojiWithCode:0x1f238]];
    [array addObject:[self emojiWithCode:0x1f202]];
    [array addObject:[self emojiWithCode:0x24c2]];
    [array addObject:[self emojiWithCode:0x1f6c2]];
    [array addObject:[self emojiWithCode:0x1f6c4]];
    [array addObject:[self emojiWithCode:0x1f6c5]];
    [array addObject:[self emojiWithCode:0x1f6c3]];
    [array addObject:[self emojiWithCode:0x1f251]];
    [array addObject:[self emojiWithCode:0x3299]];
    [array addObject:[self emojiWithCode:0x3297]];
    [array addObject:[self emojiWithCode:0x1f191]];
    [array addObject:[self emojiWithCode:0x1f198]];
    [array addObject:[self emojiWithCode:0x1f194]];
    [array addObject:[self emojiWithCode:0x1f6ab]];
    [array addObject:[self emojiWithCode:0x1f51e]];
    [array addObject:[self emojiWithCode:0x1f4f5]];
    [array addObject:[self emojiWithCode:0x1f6af]];
    [array addObject:[self emojiWithCode:0x1f6b1]];
    [array addObject:[self emojiWithCode:0x1f6b3]];
    [array addObject:[self emojiWithCode:0x1f6b7]];
    [array addObject:[self emojiWithCode:0x1f6b8]];
    [array addObject:[self emojiWithCode:0x26d4]];
    [array addObject:[self emojiWithCode:0x2733]];
    [array addObject:[self emojiWithCode:0x2747]];
    [array addObject:[self emojiWithCode:0x274e]];
    [array addObject:[self emojiWithCode:0x2705]];
    [array addObject:[self emojiWithCode:0x2734]];
    [array addObject:[self emojiWithCode:0x1f49f]];
    [array addObject:[self emojiWithCode:0x1f19a]];
    [array addObject:[self emojiWithCode:0x1f4f3]];
    [array addObject:[self emojiWithCode:0x1f4f4]];
    [array addObject:[self emojiWithCode:0x1f170]];
    [array addObject:[self emojiWithCode:0x1f171]];
    [array addObject:[self emojiWithCode:0x1f18e]];
    [array addObject:[self emojiWithCode:0x1f17e]];
    [array addObject:[self emojiWithCode:0x1f4a0]];
    [array addObject:[self emojiWithCode:0x27bf]];
    [array addObject:[self emojiWithCode:0x267b]];
    [array addObject:[self emojiWithCode:0x2648]];
    [array addObject:[self emojiWithCode:0x2649]];
    [array addObject:[self emojiWithCode:0x264a]];
    [array addObject:[self emojiWithCode:0x264b]];
    [array addObject:[self emojiWithCode:0x264c]];
    [array addObject:[self emojiWithCode:0x264d]];
    [array addObject:[self emojiWithCode:0x264e]];
    [array addObject:[self emojiWithCode:0x264f]];
    [array addObject:[self emojiWithCode:0x2650]];
    [array addObject:[self emojiWithCode:0x2651]];
    [array addObject:[self emojiWithCode:0x2652]];
    [array addObject:[self emojiWithCode:0x2653]];
    [array addObject:[self emojiWithCode:0x26ce]];
    [array addObject:[self emojiWithCode:0x1f52f]];
    [array addObject:[self emojiWithCode:0x1f3e7]];
    [array addObject:[self emojiWithCode:0x1f4b9]];
    [array addObject:[self emojiWithCode:0x1f4b2]];
    [array addObject:[self emojiWithCode:0x1f4b1]];
//    Emoji.fromChar((char)0x00a9),
//    Emoji.fromChar((char)0x00ae),
//    [array addObject:[self emojiWithCode:0xe24e]];
//    [array addObject:[self emojiWithCode:0xe24f]];
    
    [array addObject:[self emojiWithCode:0x2122]];
    [array addObject:[self emojiWithCode:0x274c]];
    [array addObject:[self emojiWithCode:0x203c]];
    [array addObject:[self emojiWithCode:0x2049]];
    [array addObject:[self emojiWithCode:0x2757]];
    [array addObject:[self emojiWithCode:0x2753]];
    [array addObject:[self emojiWithCode:0x2755]];
    [array addObject:[self emojiWithCode:0x2754]];
    [array addObject:[self emojiWithCode:0x2b55]];
    [array addObject:[self emojiWithCode:0x1f51d]];
    [array addObject:[self emojiWithCode:0x1f51a]];
    [array addObject:[self emojiWithCode:0x1f519]];
    [array addObject:[self emojiWithCode:0x1f51b]];
    [array addObject:[self emojiWithCode:0x1f51c]];
    [array addObject:[self emojiWithCode:0x1f503]];
    [array addObject:[self emojiWithCode:0x1f55b]];
    [array addObject:[self emojiWithCode:0x1f567]];
    [array addObject:[self emojiWithCode:0x1f550]];
    [array addObject:[self emojiWithCode:0x1f55c]];
    [array addObject:[self emojiWithCode:0x1f551]];
    [array addObject:[self emojiWithCode:0x1f55d]];
    [array addObject:[self emojiWithCode:0x1f552]];
    [array addObject:[self emojiWithCode:0x1f55e]];
    [array addObject:[self emojiWithCode:0x1f553]];
    [array addObject:[self emojiWithCode:0x1f55f]];
    [array addObject:[self emojiWithCode:0x1f554]];
    [array addObject:[self emojiWithCode:0x1f560]];
    [array addObject:[self emojiWithCode:0x1f555]];
    [array addObject:[self emojiWithCode:0x1f556]];
    [array addObject:[self emojiWithCode:0x1f557]];
    [array addObject:[self emojiWithCode:0x1f558]];
    [array addObject:[self emojiWithCode:0x1f559]];
    [array addObject:[self emojiWithCode:0x1f55a]];
    [array addObject:[self emojiWithCode:0x1f561]];
    [array addObject:[self emojiWithCode:0x1f562]];
    [array addObject:[self emojiWithCode:0x1f563]];
    [array addObject:[self emojiWithCode:0x1f564]];
    [array addObject:[self emojiWithCode:0x1f565]];
    [array addObject:[self emojiWithCode:0x1f566]];
    [array addObject:[self emojiWithCode:0x2716]];
    [array addObject:[self emojiWithCode:0x2795]];
    [array addObject:[self emojiWithCode:0x2796]];
    [array addObject:[self emojiWithCode:0x2797]];
    [array addObject:[self emojiWithCode:0x2660]];
    [array addObject:[self emojiWithCode:0x2665]];
    [array addObject:[self emojiWithCode:0x2663]];
    [array addObject:[self emojiWithCode:0x2666]];
    [array addObject:[self emojiWithCode:0x1f4ae]];
    [array addObject:[self emojiWithCode:0x1f4af]];
    [array addObject:[self emojiWithCode:0x2714]];
    [array addObject:[self emojiWithCode:0x2611]];
    [array addObject:[self emojiWithCode:0x1f518]];
    [array addObject:[self emojiWithCode:0x1f517]];
    [array addObject:[self emojiWithCode:0x27b0]];
    [array addObject:[self emojiWithCode:0x3030]];
    [array addObject:[self emojiWithCode:0x303d]];
    [array addObject:[self emojiWithCode:0x1f531]];
    [array addObject:[self emojiWithCode:0x25fc]];
    [array addObject:[self emojiWithCode:0x25fb]];
    [array addObject:[self emojiWithCode:0x25fe]];
    [array addObject:[self emojiWithCode:0x25fd]];
    [array addObject:[self emojiWithCode:0x25aa]];
    [array addObject:[self emojiWithCode:0x25ab]];
    [array addObject:[self emojiWithCode:0x1f53a]];
    [array addObject:[self emojiWithCode:0x1f532]];
    [array addObject:[self emojiWithCode:0x1f533]];
    [array addObject:[self emojiWithCode:0x26ab]];
    [array addObject:[self emojiWithCode:0x26aa]];
    [array addObject:[self emojiWithCode:0x1f534]];
    [array addObject:[self emojiWithCode:0x1f535]];
    [array addObject:[self emojiWithCode:0x1f53b]];
    [array addObject:[self emojiWithCode:0x2b1c]];
    [array addObject:[self emojiWithCode:0x2b1b]];
    [array addObject:[self emojiWithCode:0x1f536]];
    [array addObject:[self emojiWithCode:0x1f537]];
    [array addObject:[self emojiWithCode:0x1f538]];
    [array addObject:[self emojiWithCode:0x1f539]];
    
    return array;
}


+ (NSArray *)allEmoji {
    NSMutableArray *array = [[NSMutableArray alloc] init];
    [array addObjectsFromArray:[self peopel]];
    [array addObjectsFromArray:[self nature]];
    [array addObjectsFromArray:[self places]];
    [array addObjectsFromArray:[self objects]];
    [array addObjectsFromArray:[self symbols]];
    
    return array;
}

@end
